[project]
name = "needleinavidstack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "google-genai>=0.1.0",
    "moviepy>=2.1.1",
    "pydub>=0.25.1",
    "streamlit>=1.41.1",
]
